apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: flaskapp
          image: pvaranasi/flaskapp:5
          ports:
            - containerPort: 5000
