apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30050
